/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verify_email"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/{provider}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oauth_callback"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/{provider}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["oauth_start"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_profile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResultEmpty: {
            message: string;
            success: boolean;
        };
        ApiResult_UserProfile: {
            message: string;
            payload?: {
                avatarUrl?: string | null;
                /** Format: date-time */
                createdAt: string;
                email?: string | null;
                /** Format: date-time */
                emailVerifiedAt?: string | null;
                preferences: components["schemas"]["UserPreferences"];
                status: components["schemas"]["UserStatus"];
                /** Format: date-time */
                updatedAt: string;
                /** Format: uuid */
                userId: string;
                userTag: string;
                username: string;
            };
            success: boolean;
        };
        AuthCallbackQuery: {
            code: string;
            error?: string | null;
            error_description?: string | null;
            state?: string | null;
        };
        CreateUser: {
            email: string;
            password: string;
            username: string;
        };
        OAuthProvider:
            | "Github"
            | "Google"
            | {
                  Unknown: string;
              };
        UserPreferences: {
            locale?: string | null;
            theme?: string | null;
            timezone?: string | null;
        };
        UserProfile: {
            avatarUrl?: string | null;
            /** Format: date-time */
            createdAt: string;
            email?: string | null;
            /** Format: date-time */
            emailVerifiedAt?: string | null;
            preferences: components["schemas"]["UserPreferences"];
            status: components["schemas"]["UserStatus"];
            /** Format: date-time */
            updatedAt: string;
            /** Format: uuid */
            userId: string;
            userTag: string;
            username: string;
        };
        /** @enum {string} */
        UserStatus: "pending" | "active" | "suspended" | "deactivated" | "banned";
        VerifyEmail: {
            email: string;
            verification_code: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description Verification email sent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description User already exists */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    verify_email: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyEmail"];
            };
        };
        responses: {
            /** @description Email verified successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid or expired verification code */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    oauth_callback: {
        parameters: {
            query: {
                /** @description OAuth provider callback */
                callback: components["schemas"]["AuthCallbackQuery"];
            };
            header?: never;
            path: {
                /** @description OAuth provider */
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authentication successful */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResultEmpty"];
                };
            };
            /** @description Invalid provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResultEmpty"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResultEmpty"];
                };
            };
        };
    };
    oauth_start: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description OAuth provider to authenticate */
                provider: components["schemas"]["OAuthProvider"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirect to OAuth provider */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResultEmpty"];
                };
            };
            /** @description Invalid provider */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResultEmpty"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResultEmpty"];
                };
            };
        };
    };
    get_profile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResult_UserProfile"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResultEmpty"];
                };
            };
        };
    };
}
