packages:
  - apps/web
  - api
  - infra/dev
  - packages/*

catalog:
  "next": "16.0.10"
  "react": "19.2.3"
  "react-dom": "19.2.3"
  "typescript": "^5"
  "@types/node": "^20"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "tailwindcss": "^4"
