-- Add up migration script here

/* === types === */
create type project_status as enum ('planned', 'active', 'on_hold', 'completed', 'archived');
create type project_visibility as enum ('private', 'team', 'public');
create type project_priority as enum ('low', 'medium', 'high', 'critical');
create type task_status as enum ('backlog', 'planned', 'in_progress', 'in_review', 'blocked', 'done', 'archived');
create type task_priority as enum ('low', 'medium', 'high', 'critical');


/* === tables === */
create table projects (
    project_id uuid primary key default gen_random_uuid(),
    organization_id uuid not null references organizations (organization_id) on delete cascade,

    -- metadata
    project_name varchar(100) not null,
    description text,
    tags text[] default '{}',

    -- status
    status project_status not null default 'planned',
    visibility project_visibility not null default 'team',
    priority project_priority not null default 'low',

    -- timeline
    start_date timestamptz,
    target_date timestamptz,
    actual_end_date timestamptz,

    -- TODO: uncomment after the `organization_members` was created
    -- created_by uuid not null references organization_members (member_id),
    created_at timestamptz default now(),
    updated_at timestamptz default now(),

    unique (organization_id, project_name)
);

-- tasks
create table tasks (
    task_id int generated by default as identity primary key,
    project_id uuid not null references projects (project_id) on delete cascade,

    parent_id int references tasks (task_id) on delete cascade,

    task_key varchar(50) generated always as ('TASK-' || task_id::text) stored,
    task_name varchar(255) not null,
    description text,
    type varchar(255) default 'general',

    /* uncomment after `project_members` schema was created
    assignor uuid not null references project_members (member_id),
    assignee uuid not null references project_members (member_id),
    */

    status task_status not null default 'backlog',
    priority task_priority not null default 'low',
    tags text[] default '{}',

    estimated_hours numeric(6,2),
    actual_hours numeric(6,2) default 0,
    remaining_hours numeric(6,2),

    start_date timestamptz,
    due_date timestamptz,
    completed_at timestamptz,

    -- progress
    progress smallint default 0 check (progress between 0 and 100),

    created_at timestamptz default now(),
    updated_at timestamptz default now(),

    unique (project_id, task_name),
    check (task_id <> parent_id)
);
