import { Task, TaskType, TaskStatus, TaskPriority } from "@planora/common/types";

export const TASKS: Task[] = [
    {
        projectId: "proj-001",
        meta: {
            taskId: "task-001",
            taskName: "Design payment database schema",
            description: "Create a scalable schema for multi-currency payments",
            type: TaskType.Feature,
            assignor: "lead-01",
            assignee: "AK",
            status: TaskStatus.InProgress,
            priority: TaskPriority.High,
            tags: ["database", "payments", "backend"],
            startDate: new Date(2026, 0, 5),
            dueDate: new Date(2026, 0, 20),
            estimatedHours: 12,
            actualHours: 6,
            progress: 50,
            createdAt: new Date(2026, 0, 1),
            updatedAt: new Date(2026, 0, 10),
        },
        subtasks: [
            {
                subTaskId: "sub-001",
                name: "Define core tables",
                description: "Transactions, balances, ledgers",
                startedAt: "2026-01-05",
                createdAt: "2026-01-05",
            },
            {
                subTaskId: "sub-002",
                name: "Add indexes & constraints",
                description: "Performance & integrity",
                createdAt: "2026-01-07",
            },
        ],
        comments: [
            {
                commendId: "com-001",
                taskId: "task-001",
                author: "Alice",
                content: "Make sure FX conversion is future-proof.",
                createdAt: "2026-01-08",
            },
        ],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-002",
            taskName: "Fix webhook retry bug",
            description: "Retries are not triggered on 5xx responses",
            type: TaskType.Bug,
            assignee: "JD",
            status: TaskStatus.Blocked,
            priority: TaskPriority.Critical,
            tags: ["bug", "webhook"],
            startDate: new Date(2026, 0, 12),
            dueDate: new Date(2026, 0, 14),
            estimatedHours: 4,
            actualHours: 2,
            progress: 30,
            createdAt: new Date(2026, 0, 10),
            updatedAt: new Date(2026, 0, 12),
        },
        subtasks: [],
        comments: [
            {
                commendId: "com-002",
                taskId: "task-002",
                author: "Bob",
                content: "Blocked until infra rate-limit issue is resolved.",
                createdAt: "2026-01-12",
            },
        ],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-003",
            taskName: "Research event-driven architecture",
            description: "Evaluate Kafka vs Postgres LISTEN/NOTIFY",
            type: TaskType.Research,
            assignee: "AK",
            status: TaskStatus.Planned,
            priority: TaskPriority.Medium,
            tags: ["research", "architecture"],
            estimatedHours: 6,
            actualHours: 0,
            progress: 0,
            createdAt: new Date(2026, 0, 8),
            updatedAt: new Date(2026, 0, 8),
        },
        subtasks: [],
        comments: [],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-004",
            taskName: "Refactor settlement flow",
            description: "Remove legacy synchronous settlement logic",
            type: TaskType.Improvement,
            assignee: "AK",
            status: TaskStatus.Done,
            priority: TaskPriority.Low,
            tags: ["refactor"],
            startDate: new Date(2025, 11, 20),
            completedAt: new Date(2025, 11, 28),
            estimatedHours: 10,
            actualHours: 9.5,
            progress: 100,
            createdAt: new Date(2025, 11, 15),
            updatedAt: new Date(2025, 11, 28),
        },
        subtasks: [
            {
                subTaskId: "sub-003",
                name: "Remove legacy code",
                description: "Delete unused settlement paths",
                completedAt: "2025-12-26",
                createdAt: "2025-12-20",
            },
        ],
        comments: [
            {
                commendId: "com-003",
                taskId: "task-004",
                author: "CTO",
                content: "Great cleanup 👏",
                createdAt: "2025-12-28",
            },
        ],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-005",
            taskName: "Write API documentation",
            description: "Public API docs for partners",
            type: TaskType.Documentation,
            assignee: "Sarah",
            status: TaskStatus.InReview,
            priority: TaskPriority.Medium,
            tags: ["docs"],
            estimatedHours: 5,
            actualHours: 4,
            progress: 80,
            createdAt: new Date(2026, 0, 6),
            updatedAt: new Date(2026, 0, 11),
        },
        subtasks: [],
        comments: [],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-006",
            taskName: "Decide role-based access model",
            description: "Custom roles vs fixed roles",
            type: TaskType.Decision,
            assignee: "AK",
            status: TaskStatus.InProgress,
            priority: TaskPriority.High,
            tags: ["auth", "rbac"],
            estimatedHours: 3,
            actualHours: 1,
            progress: 40,
            createdAt: new Date(2026, 0, 9),
            updatedAt: new Date(2026, 0, 10),
        },
        subtasks: [],
        comments: [],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-007",
            taskName: "Clean up unused feature flags",
            type: TaskType.Chore,
            status: TaskStatus.Backlog,
            priority: TaskPriority.Low,
            tags: ["cleanup"],
            actualHours: 0,
            progress: 0,
            createdAt: new Date(2026, 0, 1),
            updatedAt: new Date(2026, 0, 1),
        },
        subtasks: [],
        comments: [],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-008",
            taskName: "Implement bulk task creation UI",
            type: TaskType.Feature,
            assignee: "JD",
            status: TaskStatus.Planned,
            priority: TaskPriority.High,
            tags: ["ui", "productivity"],
            estimatedHours: 8,
            actualHours: 0,
            progress: 0,
            createdAt: new Date(2026, 0, 10),
            updatedAt: new Date(2026, 0, 10),
        },
        subtasks: [],
        comments: [],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-009",
            taskName: "Archive deprecated workflows",
            type: TaskType.Chore,
            status: TaskStatus.Archived,
            priority: TaskPriority.Low,
            tags: ["maintenance"],
            actualHours: 2,
            progress: 100,
            createdAt: new Date(2025, 10, 1),
            updatedAt: new Date(2025, 10, 5),
        },
        subtasks: [],
        comments: [],
    },

    {
        projectId: "proj-001",
        meta: {
            taskId: "task-010",
            taskName: "Spike: task strategy model",
            description: "Experiment with Eisenhower-style task strategy",
            type: TaskType.Research,
            assignee: "AK",
            status: TaskStatus.InProgress,
            priority: TaskPriority.Medium,
            tags: ["experiment", "strategy"],
            estimatedHours: 4,
            actualHours: 1.5,
            progress: 35,
            createdAt: new Date(2026, 0, 11),
            updatedAt: new Date(2026, 0, 12),
        },
        subtasks: [],
        comments: [],
    },
];
